name: CD Dev/QA - Build & Deploy

on:
  push:
    branches:
      - develop # Déclenche le workflow sur un push vers la branche 'master'

# Permet d'écrire dans le GHCR (GitHub Container Registry)
permissions:
  contents: read
  packages: write
 
jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest
   
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      # --- Build et Push de l'image Docker vers GHCR ---
     
      # Prépare les tags de l'image
      - name: 2. Set Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} 
          tags: latest
         
      # Se connecte au GHCR en utilisant le GITHUB_TOKEN automatique
      - name: 3. Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
         
      # Build and Push de l'image
      - name: 4. Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

    
